# Generated by Django 5.2.17 on 2026-09-30 05:34

import agents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0020_restaurant_qr_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('code', models.CharField(help_text="Havola va ro'yxatdan o'tishda kiritiladi: ALI, JASUR25…", max_length=16, unique=True, validators=[agents.models.validate_code], verbose_name='Kodi')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa yangi restoran ham, yangi daromad ham yozilmaydi.", verbose_name='Faol')),
                ('percent', models.PositiveSmallIntegerField(default=20, verbose_name="Har to'lovdan, %")),
                ('months', models.PositiveSmallIntegerField(default=12, help_text="Restoranning birinchi to'lovidan boshlab.", verbose_name='Necha oy davomida')),
                ('first_bonus', models.PositiveIntegerField(default=30000, verbose_name="Birinchi to'lov bonusi, so'm")),
                ('invite_token', models.CharField(default=agents.models._invite_token, editable=False, max_length=32, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('telegram_username', models.CharField(blank=True, editable=False, max_length=64)),
                ('bot_state', models.CharField(blank=True, editable=False, max_length=16)),
                ('card_number', models.CharField(blank=True, max_length=19, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(blank=True, max_length=64, verbose_name='Karta egasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agentlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name="Summa, so'm")),
                ('card_number', models.CharField(max_length=19)),
                ('card_holder', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "O'tkazildi"), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('telegram_message_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='agents.agent')),
            ],
            options={
                'verbose_name': 'pul yechish',
                'verbose_name_plural': 'pul yechishlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bonus', "Birinchi to'lov bonusi"), ('percent', 'Foiz')], max_length=10)),
                ('amount', models.PositiveIntegerField(verbose_name="Summa, so'm")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='agents.agent')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_earnings', to='menu.invoice')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_earnings', to='menu.restaurant')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='agents.agentwithdrawal')),
            ],
            options={
                'verbose_name': 'agent daromadi',
                'verbose_name_plural': 'agent daromadlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='agentwithdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('agent',), name='one_pending_withdrawal_per_agent'),
        ),
        migrations.AddConstraint(
            model_name='agentearning',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice', 'kind'), name='one_earning_per_invoice_kind'),
        ),
    ]
