# Generated by Django 5.2.17 on 2026-09-30 06:00

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='applied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ariza sanasi'),
        ),
        migrations.AddField(
            model_name='agent',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Qabul qilingan'),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=60, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='agent',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ariza izohi'),
        ),
        migrations.AddField(
            model_name='agent',
            name='rejected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Rad etilgan'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(blank=True, help_text="Havola va ro'yxatdan o'tishda kiritiladi: ALI, JASUR25…", max_length=16, null=True, unique=True, validators=[agents.models.validate_code], verbose_name='Kodi'),
        ),
    ]
