# Generated by Django 5.2.17 on 2026-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_bonus',
        ),
        migrations.AddField(
            model_name='agent',
            name='first_percent',
            field=models.PositiveSmallIntegerField(default=50, verbose_name="Birinchi to'lovdan, %"),
        ),
        migrations.AlterField(
            model_name='agent',
            name='months',
            field=models.PositiveSmallIntegerField(default=12, help_text="Keyingi to'lovlar — restoranning birinchi to'lovidan boshlab shuncha oy.", verbose_name='Necha oy davomida'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='percent',
            field=models.PositiveSmallIntegerField(default=20, verbose_name="Keyingi to'lovlardan, %"),
        ),
        migrations.AlterField(
            model_name='agentearning',
            name='kind',
            field=models.CharField(choices=[('first', "Birinchi to'lov"), ('percent', "Keyingi to'lov")], max_length=10),
        ),
    ]
