# Generated by Django 5.2.17 on 2026-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_months_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Qoidalarga rozi'),
        ),
        migrations.AddField(
            model_name='agent',
            name='rules_version',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Qoidalar versiyasi'),
        ),
    ]
