# Generated by Django 5.2.17 on 2026-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_rules_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=60, verbose_name='Viloyat'),
        ),
    ]
