# Generated by Django 5.2.17 on 2026-09-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_region_label'),
        ('menu', '0022_restaurant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bot_draft',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo')], max_length=30, verbose_name='Viloyat')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('address', models.CharField(max_length=120, verbose_name="Manzil / mo'ljal")),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=60)),
                ('address_key', models.CharField(editable=False, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_added', to='agents.agent')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'borilgan joy',
                'verbose_name_plural': 'borilgan joylar',
                'ordering': ('region', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('interested', '🤝 Qiziqdi, qayta boraman'), ('connected', '✅ Ulandi'), ('other_qr', '📱 Boshqa QR menyusi bor'), ('refused', '❌ Rad etdi'), ('no_owner', "🚪 Egasi yo'q edi")], max_length=12, verbose_name='Natija')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='agents.agent')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='agents.place')),
            ],
            options={
                'verbose_name': 'tashrif',
                'verbose_name_plural': 'tashriflar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('region', 'name_key', 'address_key'), name='one_place_per_address'),
        ),
    ]
