# Generated by Django 5.2.17 on 2026-09-22 06:56

import django.db.models.deletion
import menu.models
import menu.translations
from django.conf import settings
from django.db import migrations, models


def generate_qr_token() -> str:
    """`Table` modeli bilan birga olib tashlangan — tarixiy migratsiya uchun."""
    import secrets

    return secrets.token_urlsafe(8)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('subtitle', models.JSONField(blank=True, default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('icon', models.CharField(default='utensils-crossed', max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('description', models.JSONField(blank=True, default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('ingredients', models.JSONField(blank=True, default=menu.translations.empty_translation_list, validators=[menu.translations.validate_translation_list])),
                ('price', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=4)),
                ('kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('badges', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('cuisine', models.JSONField(blank=True, default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('address', models.JSONField(blank=True, default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('hours', models.JSONField(blank=True, default=menu.translations.empty_translation, validators=[menu.translations.validate_translation])),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('instagram', models.CharField(blank=True, max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('service_charge_percent', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.CharField(choices=[('free', 'Bepul'), ('standard', 'Standard'), ('pro', 'Pro')], default='free', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('qr_token', models.CharField(default=generate_qr_token, editable=False, max_length=32, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='menu.restaurant')),
            ],
            options={
                'ordering': ('restaurant', 'number'),
            },
        ),
        migrations.CreateModel(
            name='MenuView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('scan', 'QR skaner'), ('dish_open', 'Taom ochildi')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='menu.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='menu.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='menu.table')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'number'), name='unique_table_number_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='menuview',
            index=models.Index(fields=['restaurant', 'created_at'], name='menu_menuvi_restaur_726959_idx'),
        ),
        migrations.AddIndex(
            model_name='menuview',
            index=models.Index(fields=['restaurant', 'kind', 'created_at'], name='menu_menuvi_restaur_4ffad7_idx'),
        ),
    ]
