# Generated by Django 5.2.17 on 2026-09-22 10:03

import django.db.models.deletion
import menu.translations
from django.db import migrations, models


def dish_photos_to_gallery(apps, schema_editor):
    """Har bir taomning yagona rasmini `DishPhoto` ga ko'chiradi."""
    Dish = apps.get_model("menu", "Dish")
    DishPhoto = apps.get_model("menu", "DishPhoto")
    DishPhoto.objects.bulk_create(
        [
            DishPhoto(dish_id=pk, image=photo, position=0)
            for pk, photo in Dish.objects.exclude(photo="").values_list("id", "photo")
            if photo
        ]
    )


def gallery_to_dish_photo(apps, schema_editor):
    """Orqaga: birinchi rasmni `Dish.photo` ga qaytaradi."""
    Dish = apps.get_model("menu", "Dish")
    DishPhoto = apps.get_model("menu", "DishPhoto")
    for photo in DishPhoto.objects.order_by("dish_id", "position", "id"):
        Dish.objects.filter(pk=photo.dish_id, photo="").update(image=photo.image)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='translation_meta',
            field=models.JSONField(blank=True, default=dict, validators=[menu.translations.validate_translation_meta]),
        ),
        migrations.AddField(
            model_name='category',
            name='visible_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='visible_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='translation_meta',
            field=models.JSONField(blank=True, default=dict, validators=[menu.translations.validate_translation_meta]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='languages',
            field=models.JSONField(default=menu.translations.default_languages, validators=[menu.translations.validate_languages]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('uz-Cyrl', 'Ўзбекча'), ('ru', 'Русский'), ('en', 'English'), ('tr', 'Türkçe'), ('zh', '中文'), ('ko', '한국어'), ('ar', 'العربية'), ('de', 'Deutsch')], default='uz', max_length=10),
        ),
        migrations.CreateModel(
            name='DishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='menu.dish')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        # Avval rasmlarni yangi modelga ko'chiramiz, keyin eski maydonni o'chiramiz.
        migrations.RunPython(dish_photos_to_gallery, gallery_to_dish_photo),
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
    ]
