# Generated by Django 5.2.17 on 2026-09-22 14:38

import menu.translations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_photos_languages_and_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='translation_meta',
            field=models.JSONField(blank=True, default=dict, validators=[menu.translations.validate_translation_meta]),
        ),
    ]
