# Generated by Django 5.2.17 on 2026-09-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('price_month', models.PositiveIntegerField(help_text="so'm")),
                ('price_year', models.PositiveIntegerField(help_text="so'm")),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trial_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(default='free', max_length=16),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=16)),
                ('token', models.CharField(max_length=128)),
                ('brand', models.CharField(blank=True, max_length=16)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='menu.restaurant')),
            ],
            options={
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Sinov'), ('active', 'Faol'), ('past_due', "To'lanmadi"), ('suspended', "To'xtatilgan"), ('canceled', 'Bekor qilingan')], max_length=16)),
                ('period', models.CharField(choices=[('month', 'Oylik'), ('year', 'Yillik')], default='month', max_length=8)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('autopay', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='menu.plan')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='menu.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text="so'm")),
                ('period', models.CharField(choices=[('month', 'Oylik'), ('year', 'Yillik')], max_length=8)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Amalga oshmadi'), ('refunded', 'Qaytarildi')], max_length=16)),
                ('provider_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='menu.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
