# Generated by Django 5.2.17 on 2026-09-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_migrate_plan_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='plan',
        ),
    ]
