# Generated by Django 5.2.17 on 2026-09-23 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_restaurant_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='autopay',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='canceled_at',
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('amount', models.PositiveIntegerField(help_text="so'm")),
                ('period', models.CharField(choices=[('month', 'Oylik'), ('year', 'Yillik')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('telegram_message_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='menu.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='menu.paymentreceipt'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
