# Generated by Django 5.2.17 on 2026-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_manual_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuview',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
