# Generated by Django 5.2.17 on 2026-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_pro_plan_is_not_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_original',
            field=models.ImageField(blank=True, null=True, upload_to='categories/originals/'),
        ),
        migrations.AddField(
            model_name='dishphoto',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/originals/'),
        ),
    ]
