# Generated by Django 5.2.17 on 2026-09-24 08:43

import django.db.models.deletion
import menu.models
from django.conf import settings
from django.db import migrations, models


def add_owner_members(apps, schema_editor):
    """Mavjud har bir restoran egasi `owner` a'zosiga aylanadi."""
    Restaurant = apps.get_model("menu", "Restaurant")
    RestaurantMember = apps.get_model("menu", "RestaurantMember")
    RestaurantMember.objects.bulk_create(
        [
            RestaurantMember(restaurant=restaurant, user_id=restaurant.owner_id, role="owner")
            for restaurant in Restaurant.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_working_hours_and_socials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=menu.models.generate_invite_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=menu.models.invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='menu.restaurant')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('restaurant', 'email'), name='unique_pending_invite')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Egasi'), ('manager', 'Menejer')], default='manager', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='menu.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'user'), name='unique_restaurant_member')],
            },
        ),
        migrations.RunPython(add_owner_members, migrations.RunPython.noop),
    ]
