# Generated by Django 5.2.17 on 2026-09-24 09:34

import menu.phones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_members_and_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='extra_phones',
            field=models.JSONField(blank=True, default=list, validators=[menu.phones.validate_phone_list]),
        ),
    ]
