# Generated by Django 5.2.17 on 2026-09-24 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles(apps, schema_editor):
    """Mavjud hisoblarga bo'sh profil. Telefon bilan kirganlarda `username`
    aynan raqam — uni aloqa raqami sifatida ko'chirib qo'yamiz."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("menu", "Profile")
    Profile.objects.bulk_create(
        [
            Profile(
                user=user,
                full_name=f"{user.first_name} {user.last_name}".strip(),
                contact_phone=user.username if user.username.startswith("+") else "",
            )
            for user in User.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_extra_phones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('telegram', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
