# Generated by Django 5.2.17 on 2026-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_owner_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=32, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(blank=True, max_length=120, verbose_name='Karta egasi')),
                ('support_phone', models.CharField(blank=True, max_length=32, verbose_name='Yordam telefoni')),
                ('support_telegram', models.CharField(blank=True, max_length=120, verbose_name='Yordam Telegrami')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platforma sozlamalari',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
    ]
