# Generated by Django 5.2.17 on 2026-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_listed',
            field=models.BooleanField(default=True, verbose_name="Qidiruvda ko'rinsin"),
        ),
    ]
