# Generated by Django 5.2.17 on 2026-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_restaurant_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_color',
            field=models.CharField(default='#231c17', max_length=7, verbose_name='QR rangi'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_logo',
            field=models.BooleanField(default=False, verbose_name="QR'da logotip"),
        ),
    ]
