# Generated by Django 5.2.17 on 2026-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_restaurant_qr_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_eyes',
            field=models.CharField(choices=[('square', 'Kvadrat'), ('rounded', 'Yumaloq')], default='square', max_length=16, verbose_name='QR burchaklari'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_style',
            field=models.CharField(choices=[('square', 'Klassik'), ('rounded', 'Yumaloq'), ('dots', 'Nuqtali'), ('gapped', 'Kichik kvadratlar')], default='square', max_length=16, verbose_name='QR nuqta shakli'),
        ),
    ]
