# Generated by Django 5.2.17 on 2026-09-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('menu', '0020_restaurant_qr_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='agent_attached_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
