# Generated by Django 5.2.17 on 2026-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_restaurant_agent_restaurant_agent_attached_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(blank=True, choices=[('Toshkent shahri', 'Toshkent shahri'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo')], max_length=30, verbose_name='Viloyat'),
        ),
    ]
