# Generated by Django 5.2.17 on 2026-09-30 17:14

import django.db.models.deletion
import menu.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_restaurant_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('dish_created', "Taom qo'shildi"), ('dish_updated', 'Taom tahrirlandi'), ('price_changed', "Narx o'zgardi"), ('stock_off', 'Tugadi'), ('stock_on', 'Yana bor'), ('dish_deleted', "Taom o'chirildi"), ('category_created', "Kategoriya qo'shildi"), ('category_updated', 'Kategoriya tahrirlandi'), ('category_deleted', "Kategoriya o'chirildi")], max_length=20)),
                ('target', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': "o'zgarish",
                'verbose_name_plural': "o'zgarishlar jurnali",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=menu.models.generate_invite_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=menu.models.link_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='restaurantinvite',
            name='unique_pending_invite',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurantinvite',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='restaurantinvite',
            name='permissions',
            field=models.JSONField(blank=True, default=menu.models.all_staff_permissions),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='notify_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='permissions',
            field=models.JSONField(blank=True, default=menu.models.all_staff_permissions),
        ),
        migrations.AlterField(
            model_name='restaurantinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='restaurantinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), models.Q(('email', ''), _negated=True)), fields=('restaurant', 'email'), name='unique_pending_invite'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='menu.restaurant'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramlinktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
