# Generated by Django 5.2.17 on 2026-10-03 16:31

from django.db import migrations, models


def set_half_year_price(apps, schema_editor):
    """Standart tarif: 6 oy — 549 000 so'm (oyiga 91 500, ~8% chegirma)."""
    Plan = apps.get_model("menu", "Plan")
    Plan.objects.filter(code="standard", price_half_year=0).update(price_half_year=549_000)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_telegram_staff_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_half_year',
            field=models.PositiveIntegerField(default=0, help_text="so'm, 6 oy uchun"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period',
            field=models.CharField(choices=[('month', 'Oylik'), ('half', '6 oylik'), ('year', 'Yillik')], max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='period',
            field=models.CharField(choices=[('month', 'Oylik'), ('half', '6 oylik'), ('year', 'Yillik')], max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('month', 'Oylik'), ('half', '6 oylik'), ('year', 'Yillik')], default='month', max_length=8),
        ),
        migrations.RunPython(set_half_year_price, migrations.RunPython.noop),
    ]
