# Generated by Django 5.2.17 on 2026-10-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_plan_price_half_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text="so'm")),
                ('period', models.CharField(choices=[('month', 'Oylik'), ('half', '6 oylik'), ('year', 'Yillik')], max_length=8)),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('prepared', 'Click tekshirdi'), ('paid', "To'landi"), ('canceled', 'Bekor qilindi')], default='created', max_length=16)),
                ('click_trans_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('click_paydoc_id', models.BigIntegerField(blank=True, null=True)),
                ('error_note', models.CharField(blank=True, max_length=200)),
                ('fiscalized_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_payment', to='menu.invoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_payments', to='menu.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
