# Generated by Django 5.2.17 on 2026-10-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_click_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='show_click_button',
            field=models.BooleanField(default=False, help_text="Yoqilsa to'lov sahifasida «Click orqali to'lash» tugmasi chiqadi. To'lov ishlashi uchun serverda CLICK_* kalitlari ham kerak (CLICK.md).", verbose_name="Click tugmasini ko'rsatish"),
        ),
    ]
