# Generated by Django 5.2.17 on 2026-10-03 20:56

import menu.phones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_platform_show_click_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_phones',
            field=models.JSONField(blank=True, default=list, validators=[menu.phones.validate_phone_list]),
        ),
        migrations.AlterField(
            model_name='menuview',
            name='kind',
            field=models.CharField(choices=[('scan', 'QR skaner'), ('dish_open', 'Taom ochildi'), ('delivery_call', "Yetkazib berishga qo'ng'iroq")], max_length=16),
        ),
    ]
