# Generated by Django 5.2.17 on 2026-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_delivery_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='kcal_source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('ai', 'AI taxmini')], default='manual', max_length=8),
        ),
    ]
